### ISSUE TITLE
Kiva muting notes

### ISSUE THREAD

**Issue by ToastOnInk** [arduano/Kiva#11]
Kiva keeps muting itself randomly and not playing notes, I checked my soundfont its fine. I just gotta pause it for like 10 seconds and it will replay the audio. The video is also fine

**Comment by ToastOnInk** [comment]
heres a video https://drive.google.com/file/d/1awqm7lLeHfGQGBrOdz6rlWTBbFTs_MnJ/view?usp=sharing

**Comment by arduano** [comment]
I'm not sure which audio engine you are using. If you're using pre-rendered, then the renderer might be lagging behind which causes the muting.

**Comment by ToastOnInk** [comment]
ah yes i notice the audio buffer is on 0 when it mutes ill just let it load for a while before playing then thanks
