### ISSUE TITLE
Transposing issues on Unify Deblacked

### ISSUE THREAD

**Issue by TheRedBlueCube3** [arduano/Kiva#17]

**Comment by TheRedBlueCube3** [comment]
When I try to load up Unify (deblacked), it has some transposing issues on intro and 2nd song. Any way to fix this?

**Comment by Kaydax** [comment]
This is not a kiva issue. That is an issue with the midi itself

**Comment by TheRedBlueCube3** [comment]
When I try other midis, they have the same transposing issues. (I'm on LoopMidi)

**Comment by Kaydax** [comment]
I can't reproduce this with any of my setups. Kiva and loopmidi have 0 issues with eachother and kiva does not have the ability to transpose midi output up or down

**Comment by nyxikitty** [comment]
> When I try to load up Unify (deblacked), it has some transposing issues on intro and 2nd song. Any way to fix this?

Sounds like the MIDI might have some issues with channel assignments or pitch data or just even a specific chunk in that midi had a temp or pitch change.
