### ISSUE TITLE
Antivirus prevents it from downloading

### ISSUE THREAD

**Issue by CrazyPianist2160** [arduano/Kiva#27]
hello,

when i tried downloading the installer, my computer's antivirus blocked the download and says it detected a virus. why is this happening? i'm asking because I'm trying to find a MIDI player that can play my own MIDIs with no lag and so that the keyboard would dynamically shift from 88 keys to 128 keys without any video editing (my video editing skills suck lol).

to the developers - i'm not accusing you of putting malware into the installer. i'm just wondering if the installer is safe to download and that the quarantined file below is safe to restore.

thanks!
-crazypianist2160
<img width="788" alt="Screenshot 2023-08-30 171324" src="https://github.com/arduano/Kiva/assets/143658584/408f4c61-03c2-4f90-bcf3-034f756905df">

**Comment by arduano** [comment]
This is common with indie programs that not many people know about. Also you're using McAfee lol so that's honestly part of the issue too.

But anyway, Kiva doesn't do anything special that other programs (e.g. discord) don't do, it's just that the antivirus isn't familiar with it.

**Comment by CrazyPianist2160** [comment]
okay, thank you!
