### ISSUE TITLE
Skipping Velocity 127

### ISSUE THREAD

**Issue by Vueling102** [arduano/Kiva#31]
When im playing a black midi, when there are a lot of notes i get in corner "Skpping velocity: 127" and i don't hear anything

![image](https://github.com/user-attachments/assets/81523672-bfc0-4d65-b1f1-9cee37fff10f)

Any help? Or it's a setting?

**Comment by blackmidiuser** [comment]
To fix this, in pre-render, lower the voices.

**Comment by ayomijayasekara-lang** [comment]
That is normal. This sometimes happened to me.
