### ISSUE TITLE
Notes won't show up

### ISSUE THREAD

**Issue by blulere** [arduano/Kiva#6]
There's an issue where notes won't show up in Kiva.
It seems that notes are existing, but they are fully transparent. I used the small keyboard which presses down to demonstrate that notes are being played. but don't have a colour.
I don't know why it's happening. The Random colour palette is selected.
![edit2](https://user-images.githubusercontent.com/40177441/84034772-b417cf00-a992-11ea-9993-1a774fa048a7.jpg)

**Comment by arduano** [comment]
I'm pretty sure I've seen this issue before, and blamed it on bad gpu (because kiva uses multithreaded DX11 to render notes). What are you specs?

**Comment by blulere** [comment]
> I'm pretty sure I've seen this issue before, and blamed it on bad gpu (because kiva uses multithreaded DX11 to render notes). What are you specs?

Intel Core i3-2310M (going to upgrade to i7-2620M)
Because it's a mobile CPU, they both use HD Graphics 3000
4 GB DDR3L RAM
WIndows 8.1 Pro
The latest version of Kiva that shows the notes is 1.0.5, but the framerate is bad.
It's probably an issue because my GPU doesn't support multithreading on DX11 (I know because Unity says DX11 on DX10 GPU)
There should probably be an option to disable multithreading (if there isn't already) or compatibility mode for older versions of DirectX.

**Comment by arduano** [comment]
Oh, nope, looks like that's the version we added note color unpacking in the shader to improve data transfer performance by a lot. It improved my fps by like 50%.

Basically seems like your gpu doesn't support bitwse operations on integers or something like that.

**Comment by blulere** [comment]
It's what I expect from a 2011 gaming laptop.

**Comment by Petrkiller2** [comment]
> It's what I expect from a 2011 gaming laptop.

i have a 2011 working laptop
