### ISSUE TITLE
Dropping a MIDI file from a zipped folder causes the application to freeze.

### ISSUE THREAD

**Issue by MaddyGuthridge** [arduano/Kiva#8]
# System info:
Windows 10 v1909
Intel Core i7 8550U
16 GB RAM

# Steps to reproduce:
 - Open a zipped folder containing a MIDI in Windows Explorer
 - Drag and drop the MIDI onto Kiva

# Expected outcome:
The MIDI loads normally

# Actual outcome:
Kiva's window lightens upon moving the file over it, then freezes upon dropping the file, and becomes unresponsive for an indefinite amount of time.

**Comment by arduano** [comment]
What zipping tool are you using? Can't reproduce with winrar

**Comment by MaddyGuthridge** [comment]
Not sure... it was a ZIP that was sent to me by some random on my Discord Server. Here's the actual file tho... It loads fine when I extract it.

[Link retracted at the request of the owner.]

Replacement file where the error can also be reproduced:

[i started a joke.zip](https://github.com/arduano/Kiva/files/4874830/i.started.a.joke.zip)


After you've downloaded the file I'll need to remove it since the author requested that it not be shared publicly.

**Comment by arduano** [comment]
Same deal

I download, open in winrar, drag the .mid into kiva, kiva loads it as intended

**Comment by MaddyGuthridge** [comment]
Try opening it in Windows Explorer?

**Comment by MaddyGuthridge** [comment]
When I use 7Zip I get this error
![image](https://user-images.githubusercontent.com/31365175/86531502-30a3bc00-bf05-11ea-9f8d-f7f047de3188.png)

**Comment by arduano** [comment]
I assume this is a 7z problem

when opening a file from a zip, the zip program must save it as a temporary file somewhere else and then supply the temporary path argument later. Because it works in winrar, I assume winrar doesn't correctly save the temporary file before telling the program about it.

The code is really simple here:
![image](https://user-images.githubusercontent.com/13347712/86531544-9abc6100-bf05-11ea-9b1d-287d402b1439.png)
I don't see what could go wrong

**Comment by MaddyGuthridge** [comment]
Ok so I've tried with another MIDI, which I compressed using Windows Explorer (Send To > Compressed (Zipped) Folder). Opening from Explorer yielded the same result as initially mentioned, and opening from 7Zip produces the error message.
The error with 7Zip indicates that that may be an issue on 7Zip's end, but for explorer, it looks like your app freezes with no errors.

**Comment by arduano** [comment]
What version are you on?

**Comment by MaddyGuthridge** [comment]
1.1.14

**Comment by arduano** [comment]
Does it freeze up on basically all dragged in midis from explorer?
try some well established midi that should definitely work

**Comment by MaddyGuthridge** [comment]
Works fine for extracted MIDIs. The issue is only present when using MIDIs dragged from inside ZIPs from Explorer.

**Comment by arduano** [comment]
Oh I see, just reproduced it yeah, give me a sec to figure out the problem

**Comment by arduano** [comment]
Ok after debugging this, seems like a windows explorer problem
When drag and dropping the files in, it doesn't even get recognized as a "file drag and drop", but some other form of drag and drop. It makes sense for that to happen anyway, as giving full access to a file like this would require extracting it into a temporary directory like winrar or 7z do, and explorer doesnt want to do that.

I'll try to add some checks later to prevent it from just freezing up, and actually tell the user that the drop was invalid.

**Comment by MaddyGuthridge** [comment]
Ok cool
